server:
  host: "151.217.47.77"
  port: 8080
image:
  imageWidth: 100
  imageHeight: 100
  file: "/home/arthur/workspace/pixelflut2/34c3Logo.png"
tiles:
  tileWidth: 15
  tileHeight: 15
transparency:
  enabled: true
  transparentR: 0
  transparentG: 0
  transparentB: 0