host: "127.0.0.1"
port: 8181
width: 1024
height: 1024
imageWidth: 100
imageHeight: 100
tileWidth: 15
tileHeight: 15
file: "/home/arthur/workspace/pixelflut2/k4.png"
transparency:
    enabled: true
    transparentR: 0
    transparentG: 0
    transparentB: 0
